# Generated by Django 2.2.7 on 2019-11-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobileno',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
